### ISSUE TITLE
Fix search: Single postal codes should work

### ISSUE THREAD

**Issue by cnasenberg** [Diconium-WirVsVirus/dds-wvv-backend#42]
Our search cannot handle single postal codes at the moment. 

As a customer, I want to enter a zip code and get in return all stores in my area. 

Acceptance Criteria 
- When searching for only a postal code, I get a subset of stores only around the given area.

**Comment by PapaBravo** [comment]
Searching for postal code doesn't seem to work properly in Google Places API. When searching for `10967` it doesn't resolve to Neukölln but instead to [Texas](https://goo.gl/maps/W7k5qHhgnWVKTYdq6). I'll check if I can add some location bias (maybe by IP?) to the Google Places Search

**Comment by PapaBravo** [comment]
We are using the `GeocodingAPI.geocode` to search for our user inputs. According to the [Best Practices](https://developers.google.com/maps/documentation/geocoding/best-practices) we should be using the Google Places API instead.

> In general, use the Geocoding API when geocoding complete addresses (for example, “48 Pirrama Rd, Pyrmont, NSW, Australia”). Use the Places API Place Autocomplete service when geocoding ambiguous (incomplete) addresses or for latency-sensitive applications, like when responding to user input.

The [AutoComplete API](https://developers.google.com/places/web-service/autocomplete) allows us to restrict results to Germany. The API also automatically biases based on the request IP address. This may be a future problem as the IP address of the Backend server is used instead of the customer device.
